
{REDUND_ERROR} {REDUND_UNREPLICABLE} FUNCTION_BLOCK DummyFub (* *) (*$GROUP=User,$CAT=User,$GROUPICON=User.png,$CATICON=User.png*)
	VAR_INPUT
		enable : {REDUND_UNREPLICABLE} BOOL;
	END_VAR
END_FUNCTION_BLOCK
